platform :ios, '10.0'

def shared_pods
use_frameworks! 
pod 'Alamofire'
pod 'AlamofireImage'
# pod 'ImageSlideshow', '~> 1.8'
# pod "ImageSlideshow/Alamofire"
pod 'McPicker'
pod 'Stripe'
end

target 'Monetizr-v3-sample-app' do
    shared_pods
end