platform :ios, '10.0'

def shared_pods
use_frameworks! 
pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage'
pod 'ImageSlideshow', '~> 1.6'
pod "ImageSlideshow/Alamofire"
pod "Mobile-Buy-SDK"
pod 'McPicker'
end

target 'Monetizr-v3-sample-app' do
    shared_pods
end
